### ISSUE TITLE
Getting ready to release the next version

### ISSUE THREAD

**Issue by julienben** [react-boilerplate/react-boilerplate#2327]
Hey everyone,

Our last release 3.6 was already over 2 months ago. We haven't made any serious changes to the architecture or the stack since but I propose releasing 3.7 anyway.

It includes quite a few bug fixes as well as major upgrades for Babel and ESLint.

I think it would be great if we could include @gretzky's work from #2257 if we can finish it up soon-ish.

It's also a good opportunity to update the docs and add details/links about SSR, Electron and Docker as discussed in various issues. Relevant contributors are invited to take care of that in the relevant places (#2306, #2282, #2288).

Thoughts anyone? Have I missed anything?

**Comment by jwinn** [comment]
@julienben I'd like to update our CI to use latest and LTS versions and make sure #2304 is fixed for windows. I'll create a branch for these two items...

**Comment by jwinn** [comment]
Also, what's everyone's thoughts on running `npm audit` (`npm audit fix`), which requires adding `package-lock.json` file?

**Comment by julienben** [comment]
You can create a `package-lock` with `npm i --package-lock-only` but if we're gonna do this, are there any reasons not to switch to `npm` entirely?

**Comment by jwinn** [comment]
I know, wanted to more discuss `yarn` vs. `npm`, but should probably saved that for a later discussion. Wanted to see if `npm audit` had enough of an advantage (more from a maintenance perspective) to switch back.

**Comment by jwinn** [comment]
Agreed. I'm not sure how big of a "change" this is as to whether it requires maintainer buyoff per our guidelines. @mxstbr thoughts?

**Comment by justingreenberg** [comment]
fwiw i support switching back to npm, there were very good reasons to use yarn 2 years ago but npm has really come a long way... yarn workspaces are useful for monorepo/library ecosystem maintenance, but i think new  features (especially adding vuln auditing and `npm ci` for ) will add value to end users of this project, and as mentioned lockfile ensures builds are deterministic

the one caveat is that yarn does seem to still be slightly faster, especially when packages are cached (https://github.com/pnpm/node-package-manager-benchmark).. may be prudent to benchmark before making a final decision

**Comment by michaelcuneo** [comment]
ooh. I like this. I didn't know this about Yarn vs NPM. I'll switch back to NPM.

**Comment by julienben** [comment]
Update:

We've implemented the switch to `npm` and still working on the Babel 6 -> 7 transition (in #2331 especially).

There's still more planned including @gretzky's Webpack work and a few useful doc additions. 

If anyone else would like to bring some improvements, now is the perfect time.

**Comment by julienben** [comment]
Just as an fyi, I'm gonna be traveling from tomorrow until the end of the month. Might answer an issue here or there but won't be doing any work outside of that.

**Comment by julienben** [comment]
Btw, is anyone interested in trying to replace Immutable with something that's still being maintained and perhaps with a simpler API? We can think about Immer or other possibilities.

**Comment by mjangir** [comment]
@julienben Raised a pull request regarding #2288

**Comment by aarjithn** [comment]
👍 for Immer. https://www.netlify.com/blog/2018/09/12/the-rise-of-immer-in-react/

**Comment by gretzky** [comment]
Plugging #2092 again.

**Comment by julienben** [comment]
Here's IMO the ideal to-do list for a next version:

- [ ] Remove Immutable.js entirely (#2092) or replace it with [Immer](https://github.com/mweststrate/immer) or [seamless-immutable](https://github.com/rtfeldman/seamless-immutable)
- [ ] Move docs to Gitbook (#951)
- [ ] Fix all issues with saga injections (#2021, #2121, #2266, #2314)
- [ ] Switch to reach-router or replace abandoned react-router-redux with connected-react-router (#2354)
- [ ] Fix for extract-intl script broken by Babel 7 changes (#2331, #2350)
- [ ] Many Webpack improvements (#2257)

And the changelog so far:

- Switch from Yarn back to npm
- Upgrades to Babel 7, ESLint 5 and more
- Many documentation updates including new section for forks
- Bug fixes for generators, template app, scripts, and more

**Comment by arthurCormack** [comment]
heads up: `react-router-redux package is now deprecated` ... https://github.com/ReactTraining/react-router

**Comment by julienben** [comment]
Thanks for the heads up. Already taken care of in #2375 though.
